export const DELETE_CATEGORY_REQUEST = 'app/Categories/DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'app/Categories/DELETE_CATEGORY_SUCCESS';

export const CREATE_NEW_CATEGORY_REQUEST =
  'app/Categories/CREATE_NEW_CATEGORY_REQUEST';
export const CREATE_NEW_CATEGORY_SUCCESS =
  'app/Categories/CREATE_NEW_CATEGORY_SUCCESS';

export const EDIT_CATEGORY_REQUEST = 'app/Categories/EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_SUCCESS = 'app/Categories/EDIT_CATEGORY_SUCCESS';
