export const ROOT = '/app';

export const ROOT_ROUTES = {
  CATEGORIES_ROUTE: `${ROOT}/categories`,
  USER_SETTINGS_ROUTE: `${ROOT}/user-profile`,
  FINANCIAL_RECORDS_ROUTE: `${ROOT}/financial-records`,
};

export const USER_PROFILE_PAGES = {
  PERSONAL_INFORMATION: 'personal-information',
  ACCOUNT_SECURITY: 'security',
  CHANGE_PASSWORD: 'change-password',
  DELETE_ACCOUNT: 'delete-account',
};

export const USER_PROFILE_ROUTES = {
  PERSONAL_INFO_ROUTE: `${ROOT_ROUTES.USER_SETTINGS_ROUTE}/${
    USER_PROFILE_PAGES.PERSONAL_INFORMATION
  }`,
  SECURITY_ROUTE: `${ROOT_ROUTES.USER_SETTINGS_ROUTE}/${
    USER_PROFILE_PAGES.ACCOUNT_SECURITY
  }`,
  CHANGE_PASSWORD_ROUTE: `${ROOT_ROUTES.USER_SETTINGS_ROUTE}/${
    USER_PROFILE_PAGES.CHANGE_PASSWORD
  }`,
  DELETE_ACCOUNT_ROUTE: `${ROOT_ROUTES.USER_SETTINGS_ROUTE}/${
    USER_PROFILE_PAGES.DELETE_ACCOUNT
  }`,
  LOGOUT_ROUTE: `${ROOT_ROUTES.USER_SETTINGS_ROUTE}/#`,
};
