export const GET_USER_CATEGORIES_REQUEST = 'GET_USER_CATEGORIES_REQUEST';
export const GET_USER_CATEGORIES_SUCCESS = 'GET_USER_CATEGORIES_SUCCESS';

export const SET_NO_CATEGORIES = 'SET_NO_CATEGORIES';
